# Generated by Django 3.1.2 on 2020-11-24 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_file_path', models.CharField(max_length=200)),
                ('preview_file_url', models.CharField(max_length=200)),
                ('caff_file', models.FileField(upload_to='uploads')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_animation_set', to=settings.AUTH_USER_MODEL)),
                ('users_purchased', models.ManyToManyField(related_name='purchased_animation_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animation.animation')),
            ],
        ),
    ]
